### ISSUE TITLE
Tips for finding the decryption key

### ISSUE THREAD

**Issue by drego85** [ZapDissaster/smp2mp3#8]
[deleted]

**Comment by tintifaxe** [comment]
I guess that the keys are the same on any F*-box.

To decode, I assumed the box would have some XOR encoding similar to the other boxes from the same manufacturer.
So I manually brute-forced one of the .mki files, trying to use an XOR decoder first (which didn't work). Then, I tried every possibility of bit rotation (-7 to +7) followed by an XOR decoder until I had an ID3 signature in the HEX editor. This was it.

To back up the files from your box, you need the original cable (I'm not sure if this is because many micro USB cables do not transfer data or because the pins in the original cable are somewhat different).
Conversion with smp2mp3 only worked in "directory" mode. I assume the conversion of single files expects .smp files.

You can then easily replace the files from the folders to which you have NFC tags with your own (converted) mp3 files.
Or write some own tags to access folders (and files) you will never need (because of another language)

Here is the screenshot of the decrypting algorithm:
![Algorithm](https://github.com/ZapDissaster/smp2mp3/assets/137358209/739ae3f1-9a09-40d9-925c-cfb798ad7309)

**Comment by drego85** [comment]
**First of all, thank you!** You allowed me to understand why I couldn't create a backup!

I needed to convert the entire directory and not the individual file. I will finally have a backup of my characters.

Some details that may be helpful to you:
1. The original MicroUSB cable has a longer plug than usual, and the outer box is very thick. But it is a very normal MicroUSB cable.
2. Inside the box is a very normal MicroSD, you can take it out and read it in your PC
3. Perhaps the directory name is crucial in the decoding process; if you move files from directory XX to directory YY, the box will no longer play the music.

Finally I want to ask you the last question, I saw that you dumped NFC with Flipper Zero. Were you able to transfer the content to a new NFC tag? I can't even emulate it with the Flipper Zero. Any suggestions?

**Comment by tintifaxe** [comment]
The codes on the tags (figurines) have the format 02190530 **0015** 00, with the four digits in bold (0015) corresponding to the folder on the box.
When you replace files on the SD card, you must make sure that your .mp3 files have an ID3 tag (in the title) before converting them to mki files.
for example K0016CP02
means: folder K0016 and Track CP02

I didn't manage to emulate consistently with the flipper, and I think that the reason is a misalignment between the antennas.
Nevertheless, I was successful in using cheap NTAG213 NFC tags (from Amazon), which I programmed with my phone (take care, sometimes they get very hot while writing and break). For them to work, they must be placed exactly centred and flush on the box. I don't think NFC cards will work equally good, as they will leave a small gap and will be hard to align. Let me know if you manage to use other NFC tags, cards, or the flipper.

**Comment by drego85** [comment]
Thank you, obviously I'm not so lucky!  😅

Through the application "NFC TagWriter by NXP" I'm importing a CVS file that has this content:

```
Type (Link, Text);Content (http://....);URI type (URI, URL, File...);Description;Interaction counter;UID mirror;Interaction counter mirror
Text;02190530001500;en;0015;no;no;no
```

The content was generated through smp2mp3 I only changed the ID to the one you suggested.

But I have already tried two NFC tags with no success :(  I'm using [these tags](https://www.amazon.it/dp/B0C7811YKJ), maybe they are too cheap. 🤷‍♂️

Can you link the ones you bought? So I'm sure...

Thanks!

**Comment by drego85** [comment]
I just realized that I bought N213 tags but they are 203!  🤬

If you send me the link of the ones you bought maybe I will be luckier! 🤞

**Comment by tintifaxe** [comment]
I was using those tags: https://amzn.eu/d/5L06Rf1
If I recall correctly, they were the ones used in the figurine (you can shine light through the socket).
The code 0219053000150 is the one on the elephant (in French). You might try another app to write (NFC tools).
Or try with the flipper on an open box. :)

**Comment by drego85** [comment]
Okay, thank you very much! I was able to create a backup of my two characters.

**Comment by Fullmetal11** [comment]
> Okay, thank you very much! I can probably create a backup of my characters.

Ciao @Andrea, ho utilizzato smp2mp3 per criptare con successo alcuni miei files .mp3 trasferendoli all'interno del FABA in formato .mki.
Vorrei ora programmare un TAG NFC in modo che appoggiandolo sopra mi faccia partire le canzoni di quella cartella ma non ci riesco, ho provato molte volte e in vari modi senza successo, anche modificando il csv creato dal programma smp2mp3 e scrivendolo con  NFC TagWriter by NXP.

Ho provato inoltre a copiare il TAG NFC dell'elefantino con NFC tools (lettura dall'elefante originale e copia diretta su un nuovo TAG) ma se appoggio il nuovo TAG sopra al FABA non succede nulla. I TAG sono gli stessi N213 indicati da tintifaxe.


Hello, @drego85 can you explain me how to  transfer the content of an original figurine to a new NFC tag?
I don't have flipper, i tryed to use NFC TagWriter by NXP and NFC tools without success.
Tags are the same here https://amzn.eu/d/5L06Rf1 (tintifaxe).
